name       : lxd
version    : "4.20"
release    : 2
source     :
    - https://linuxcontainers.org/downloads/lxd/lxd-4.20.tar.gz : 35504ef2e2dc7024b7088010987657969b1e2dea5581b24b4294f8f449248ed5
license    : Apache-2.0
homepage   : https://linuxcontainers.org/lxd/introduction/
component  : virt
summary    : Daemon based on liblxc offering a REST API to manage containers
description: |
    LXD is a next generation system container and virtual machine manager. It offers a unified user experience around full Linux systems running inside containers or virtual machines.
builddeps  :
    - pkgconfig(dqlite)
    - pkgconfig(libacl)
    - pkgconfig(libcap)
    - pkgconfig(libuv)
    - pkgconfig(lxc)
    - pkgconfig(raft)
    - pkgconfig(sqlite3)
    - golang
rundeps    :
    - ebtables
    - lxcfs
    - rsync
setup      : |
    mkdir bin
build      : |
    export GOFLAGS="-buildmode=pie -trimpath"
    export CGO_LDFLAGS_ALLOW="-Wl,-z,now"

    go build -v -tags "netgo" -o bin/ ./lxd-p2c/...
    CGO_LDFLAGS="$LDFLAGS -static" go build -v -tags "agent" -o bin/ ./lxd-agent/...
    for tool in fuidshift lxc lxc-to-lxd lxd lxd-benchmark; do
        go build -v -tags "libsqlite3" -o bin/ ./$tool/...
    done
install    : |
    for tool in fuidshift lxc lxc-to-lxd lxd lxd-agent lxd-benchmark lxd-p2c; do
        install -p -Dm00755 bin/$tool $installdir/usr/bin/$tool
    done

    # Bash completions
    install -p -Dm00644 scripts/bash/lxd-client $installdir/usr/share/bash-completion/completions/lxd

    install -Dm00644 $pkgfiles/lxd.sysusers $installdir/%libdir%/sysusers.d/lxd.conf
    install -Dm00644 $pkgfiles/lxd.tmpfiles $installdir/%libdir%/tmpfiles.d/lxd.conf
    install -Dm00644 $pkgfiles/lxd.service $installdir/%libdir%/systemd/system/lxd.service
    install -Dm00644 $pkgfiles/lxd.socket $installdir/%libdir%/systemd/system/lxd.socket
